#!/bin/bash

LOGS="./target"

./run-sales-read-back > ${LOGS}/sales-read-back.log 2>&1 &
./run-sales-read-front > ${LOGS}/sales-read-front.log 2>&1 &
./run-sales-write-back > ${LOGS}/sales-write-back.log 2>&1 &
./run-sales-write-front > ${LOGS}/sales-write-front.log 2>&1 &
