package ecommerce.sales

import pl.newicom.dddd.view.sql.SqlViewStoreConfiguration
import pl.newicom.eventstore.EventStoreConfiguration

trait SalesReadBackendConfiguration extends SqlViewStoreConfiguration with EventStoreConfiguration
